version: '3.8'
services:
  zookeeper:
    image: debezium/zookeeper:2.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - cdc-network

  kafka:
    image: debezium/kafka:2.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - cdc-network

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    depends_on:
      - kafka
    networks:
      - cdc-network

  postgres:
    image: postgres:15.2-alpine3.17
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres-config/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - cdc-network

  connect:
    image: debezium/connect:2.1
    container_name: connect
    ports:
      - "8083:8083"
    environment:
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses
      BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
      - postgres
    networks:
      - cdc-network

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"  # HTTP interface
      - "9001:9000"  # Native interface
    depends_on:
      - kafka
    networks:
      - cdc-network

networks:
  cdc-network:
    driver: bridge
